### ISSUE TITLE
requires Python >=3.7

### ISSUE THREAD

**Issue by bertsky** [ocr-d-modul-2-segmentierung/ocrd-pixelclassifier-segmentation#15]
On Python 3.6, you currently get this:

```
File "ocrd_pc_segmentation/cli.py", line 4, in <module>
    from ocrd_pc_segmentation.ocrd_segmentation import PixelClassifierSegmentation
  File "ocrd_pc_segmentation/ocrd_segmentation.py", line 6, in <module>
    from ocr4all.colors import ColorMap
  File "ocr4all/colors.py", line 1
    from __future__ import annotations
```

So one of the dependents obviously lacks a `python_requires='>=3.7'`, confusing `pip` et al. With all the layers of repos and packages, which seem to be renamed every now and then, I have not been able to trace where exactly this happens, presumably `ocr4all-pylab` (which is on your [Gitlab](https://gitlab2.informatik.uni-wuerzburg.de/ocr4all-page-segmentation/pylib.git) where I cannot open issues).

But please add that statement to setup.py at least here.

**Comment by bertsky** [comment]
Or better yet, and since OCR-D requires supportin 3.6 as well, rewrite `ocrd4all.colors` to _not_ rely on type annotations. You can easily do that by replacing `-> ColorMap` with `-> 'ColorMap'` (and removing the future import).

**Comment by kba** [comment]
> Or better yet, and since OCR-D requires supportin 3.6 as well, rewrite `ocrd4all.colors` to _not_ rely on type annotations. You can easily do that by replacing `-> ColorMap` with `-> 'ColorMap'` (and removing the future import).

I second that, I understand that type annotations are a desirable feature but we will have to support Python 3.6 for a while longer.

**Comment by crater2150** [comment]
I had set Pycharm to check for 3.6 compatibility, but it didn't mark annotations as incompatible. I changed it to a string like @bertsky recommended (release `ocr4all-pylib==0.2.5`).

As the Pycharm inspection doesn't seem reliable, and I haven't started using python before 3.7 was released, I'll check the rest of the code for compatibility. But as far as I can tell from a quick glance, dataclasses should be the only other 3.7 feature used, and they are handled as a package dependency for 3.6, and the tests for `ocr4all-pylib` run with python3.6

**Comment by bertsky** [comment]
@crater2150 Many thanks for this quick fix!

It does work for me if I upgrade `ocr4all-pylib` to 0.2.6 **manually**. But if I just install ocrd_pc_segmentation, I get 0.2.3.

Digging into it, I found that `make deps` actually uses a dynamically created `requirements.txt` (which was still old in my case). Do you think you can change the makefile to force updating that file?

**Comment by crater2150** [comment]
@bertsky For me, `make deps` always regenerates `requirements.txt`, as the target already has a dependency on the `.PHONY` target `pip-tools`, but I added an additional `.PHONY` for `requirements.txt`, so `make` should always start a build.
I suspect the actual problem was `pip-compile`'s own cache, I added a flag to its call that should disable it. Can you try if this causes the dependency to update (if you have the old requirements file still around)?

**Comment by bertsky** [comment]
@crater2150 thanks! I did not have an old `requirements.txt` around, but I faked one (with `ocr4all-pylib==0.2.3` and an old date stamp). Unfortunately, after pulling 355648093022fdea726ea457451b007c8cb4b91c it still did not update my `requirements.txt` automatically (I would have to remove it to get `ocr4all-pylib==0.2.6`).

See log attached.
[make-deps.zip](https://github.com/ocr-d-modul-2-segmentierung/ocrd-pixelclassifier-segmentation/files/5385216/make-deps.zip)

**Comment by crater2150** [comment]
It seems that the help output of pip-compile is a bit misleading, I assumed "Clear any caches upfront, rebuild from scratch" would mean, that a preexisting `requirements.txt` wouldn't have impact on the result. The flag actually needed is `--upgrade`, which I now added to the Makefile and tested it with a faked `requirements.txt` like yours. `make deps` now seems to correctly upgrade to the latest compatible version.

**Comment by bertsky** [comment]
That did the trick – thanks a lot, @crater2150 !
