### ISSUE TITLE
use OCR-D CLI

### ISSUE THREAD

**Issue by bertsky** [ocr-d-modul-2-segmentierung/ocrd-pixelclassifier-segmentation#2]
From the naming I assume you want to conform to [OCR-D/spec](https://ocr-d.github.io/spec/cli) with `ocrd-pc-seg-process`. Please do so. 

BTW, the easiest way to get there is using OCR-D/core's CLI decorators, as done by [most modules](https://github.com/topics/ocr-d), not `argparse`.

Also, for the implementation of it, it is not [compliant](https://ocr-d.github.io/mets) to simply write to _some_ PAGE-XML and be done with it. You have to open the specific PAGE files of the input file group in the METS, and create new files under the output file group, which you have to register with METS. 

Again, all this is really easy to do with OCR-D/core's `Processor` class.

**Comment by crater2150** [comment]
The code has undergone a larger refactoring and should now be conforming to the CLI spec.

Most of the program logic has moved into the page-segmentation package, while this repository now contains the OCR-D specific parts including a CLI using the provided decorators. I've based my code on the scripts from [the tesserocr wrapper](https://github.com/OCR-D/ocrd_tesserocr).
I've not yet tested it with the rest of the workflow, I'll try to do that shortly.

**Comment by crater2150** [comment]
The CLI now no longer has mandatory parameters (there is a default model packaged with the module), and a minimal test has been added to the Makefile and seems to work without problems.

**Comment by bertsky** [comment]
Excellent, thanks @crater2150!
