### ISSUE TITLE
makefile: install must depend on deps

### ISSUE THREAD

**Issue by bertsky** [ocr-d-modul-2-segmentierung/ocrd-pixelclassifier-segmentation#3]
`install` must specify its dependencies. That's what the makefile is there for: encapsulate dependencies.

If you want to differentiate different installation options, use environment variables or GPU detection.

**Comment by bertsky** [comment]
Besides, I don't think `pip install -e .` is a good choice for a makefile recipe. The source and target should normally be independent.

**Comment by crater2150** [comment]
I copied the makefile from another repo, but have now changed it accordingly. You're right, the `-e` switch doesn't make sense here.

The `deps` target now installs the CPU variant of tensorflow by default, to use GPU the environment variable `TENSORFLOW_GPU` has to be set (will document that in the README, of course). Do you know of any other ocrd projects doing something similar and already using another variable name?

I haven't yet found a reliable GPU detection method, especially one that detects CuDNN availability across different distributions (which is required for Tensorflow-GPU to work).

**Comment by bertsky** [comment]
> The `deps` target now installs the CPU variant of tensorflow by default, to use GPU the environment variable `TENSORFLOW_GPU` has to be set (will document that in the README, of course).

Great, thanks!

> Do you know of any other ocrd projects doing something similar and already using another variable name?

In my own [cor-asv-ann](https://github.com/ASVLeipzig/cor-asv-ann) I simply require `tensorflow`, because custom bazel builds (CPU or GPU) also export that package name. Moreover, I made my network setup independent of whether CuDNN was installed: I make sure that `LSTM` uses the exact same parameters as `CuDNNLSTM` and have Tensorflow tell me whether there is a GPU at runtime. (Then I configure my model with either `LSTM` or `CuDNNLSTM` and load the weights into that.) So it is independent.

As for others, I don't know. But likely!

> I haven't yet found a reliable GPU detection method, especially one that detects CuDNN availability across different distributions (which is required for Tensorflow-GPU to work).

True. At least not from outside Python. You would need to include the CuDNN self-test binary (which is kind of circular).
